import { writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_URL = 'https://raw.githubusercontent.com/codebox/HYG-Database/master/hygdata_v3.csv';
const OUTPUT_URL = new URL('./src/data/starCatalog.ts', import.meta.url);
const MAG_LIMIT = 6.5;
const COORD_BUCKET = 0.0001;
const REQUIRED_COLUMNS = ['ra', 'dec', 'mag', 'ci', 'hip', 'hd', 'hr', 'dist'];

function parseCsvLine(line) {
  const fields = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (inQuotes) {
      if (char === '"') {
        if (line[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += char;
      }
    } else if (char === '"') {
      inQuotes = true;
    } else if (char === ',') {
      fields.push(field);
      field = '';
    } else {
      field += char;
    }
  }
  fields.push(field);
  return fields;
}

function toNumber(value, fallback = 0) {
  const n = Number.parseFloat(value);
  return Number.isFinite(n) ? n : fallback;
}

function roundTo(value, decimals) {
  const factor = 10 ** decimals;
  return Math.round(value * factor) / factor;
}

async function fetchCsv() {
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    throw new Error(`Failed to fetch HYG dataset: ${res.status} ${res.statusText}`);
  }
  return res.text();
}

function parseRows(csv) {
  const clean = csv.replace(/^\uFEFF/, '');
  const lines = clean.split(/\r\n|\n/).filter((line) => line.trim().length > 0);

  const header = parseCsvLine(lines[0]).map((name) => name.trim());
  const col = Object.fromEntries(header.map((name, i) => [name, i]));

  for (const name of REQUIRED_COLUMNS) {
    if (!(name in col)) {
      throw new Error(`HYG schema missing expected column: ${name}`);
    }
  }

  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const fields = parseCsvLine(lines[i]);

    const mag = toNumber(fields[col.mag]);
    if (mag > MAG_LIMIT) continue;

    const dist = toNumber(fields[col.dist]);
    if (dist === 0) continue;

    const hip = toNumber(fields[col.hip], 0);
    const hd = (fields[col.hd] ?? '').trim();
    const ra = toNumber(fields[col.ra]);
    const dec = toNumber(fields[col.dec]);
    const ciRaw = fields[col.ci];
    const ci = ciRaw === undefined || ciRaw === '' ? 0.0 : toNumber(ciRaw);

    rows.push({ hip, hd, ra, dec, mag, ci });
  }
  return rows;
}

function dedupe(rows) {
  const groups = new Map();

  for (const star of rows) {
    let key;
    if (star.hip > 0) {
      key = `HIP:${star.hip}`;
    } else if (star.hd !== '') {
      key = `HD:${star.hd}`;
    } else {
      const raBucket = Math.round(star.ra / COORD_BUCKET);
      const decBucket = Math.round(star.dec / COORD_BUCKET);
      key = `XY:${raBucket}:${decBucket}`;
    }

    const existing = groups.get(key);
    if (!existing || star.mag < existing.mag) {
      groups.set(key, star);
    }
  }

  return [...groups.values()].sort((a, b) => a.hip - b.hip);
}

function toTuples(stars) {
  return stars.map((s) => [
    s.hip,
    roundTo(s.ra, 6),
    roundTo(s.dec, 6),
    roundTo(s.mag, 3),
    roundTo(s.ci, 3),
  ]);
}

function toModule(tuples) {
  const rows = tuples.map((t) => `  [${t.join(', ')}],`).join('\n');
  return `// Auto-generated by generate-stars.mjs from the HYG database. Do not edit by hand.
export type StarTuple = [hipId: number, raHours: number, decDegrees: number, magnitude: number, bvColorIndex: number];

export const STAR_CATALOG: StarTuple[] = [
${rows}
];
`;
}

async function main() {
  const csv = await fetchCsv();
  const rows = parseRows(csv);
  const deduped = dedupe(rows);
  const tuples = toTuples(deduped);
  const module = toModule(tuples);

  const outPath = fileURLToPath(OUTPUT_URL);
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, module, 'utf8');

  console.log(`Parsed ${rows.length} candidate rows, wrote ${tuples.length} deduplicated stars to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
